/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author jrodriguez
 */
public class frmAsiento extends javax.swing.JFrame {
    
    private javax.swing.JButton asientoSeleccionado = null;
    
    
  
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmAsiento.class.getName());

    /**
     * Creates new form frmAsiento
     */
    public frmAsiento() {
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtIdUsuario = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        btnGuardar1 = new javax.swing.JButton();
        btnGuardar2 = new javax.swing.JButton();
        btnGuardar3 = new javax.swing.JButton();
        btnGuardar4 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        btnGuardar5 = new javax.swing.JButton();
        btnGuardar6 = new javax.swing.JButton();
        btnGuardar7 = new javax.swing.JButton();
        btnGuardar8 = new javax.swing.JButton();
        btnGuardar9 = new javax.swing.JButton();
        btnGuardar10 = new javax.swing.JButton();
        btnGuardar11 = new javax.swing.JButton();
        btnGuardar12 = new javax.swing.JButton();
        btnGuardar13 = new javax.swing.JButton();
        btnGuardar14 = new javax.swing.JButton();
        btnGuardar15 = new javax.swing.JButton();
        btnGuardar16 = new javax.swing.JButton();
        btnGuardar17 = new javax.swing.JButton();
        btnGuardar18 = new javax.swing.JButton();
        btnGuardar19 = new javax.swing.JButton();
        btnGuardar20 = new javax.swing.JButton();
        btnGuardar21 = new javax.swing.JButton();
        btnGuardar22 = new javax.swing.JButton();
        btnGuardar23 = new javax.swing.JButton();
        btnGuardar24 = new javax.swing.JButton();
        btnGuardar25 = new javax.swing.JButton();
        btnGuardar26 = new javax.swing.JButton();
        btnGuardar27 = new javax.swing.JButton();
        btnGuardar28 = new javax.swing.JButton();
        btnGuardar29 = new javax.swing.JButton();
        btnGuardar30 = new javax.swing.JButton();
        btnGuardar31 = new javax.swing.JButton();
        btnGuardar32 = new javax.swing.JButton();
        btnGuardar33 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();

        txtIdUsuario.setBackground(new java.awt.Color(227, 242, 253));
        txtIdUsuario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtIdUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdUsuarioActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("frmAsiento");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Leyenda");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Vuelo:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Asiento Del Vuelo:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("A");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vuelo 1 - 15/08/2026 - 08:00 1", "Vuelo 2 - 15/08/2026 - 14:00 2", "Vuelo 3 - 16/08/2026 - 10:00 3", "Vuelo 5-  16/08/2026 - 09:00 4" }));

        btnGuardar1.setBackground(new java.awt.Color(1, 86, 192));
        btnGuardar1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGuardar1.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosAerofly/agregar (4).png"))); // NOI18N
        btnGuardar1.setText("Seleccionar");
        btnGuardar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar1ActionPerformed(evt);
            }
        });

        btnGuardar2.setBackground(new java.awt.Color(1, 86, 192));
        btnGuardar2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGuardar2.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosAerofly/salidaAvion.png"))); // NOI18N
        btnGuardar2.setText("Selección De Asientos");
        btnGuardar2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar2ActionPerformed(evt);
            }
        });

        btnGuardar3.setBackground(new java.awt.Color(1, 86, 192));
        btnGuardar3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGuardar3.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosAerofly/buscar.png"))); // NOI18N
        btnGuardar3.setText("Actualizar");
        btnGuardar3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar3ActionPerformed(evt);
            }
        });

        btnGuardar4.setBackground(new java.awt.Color(153, 255, 153));
        btnGuardar4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGuardar4.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosAerofly/plano.png"))); // NOI18N
        btnGuardar4.setText("1A");
        btnGuardar4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar4ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("B");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("C");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("E");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("D");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("F");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("1");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText("2");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setText("3");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setText("4");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setText("5");

        btnGuardar5.setBackground(new java.awt.Color(153, 255, 153));
        btnGuardar5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGuardar5.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosAerofly/plano.png"))); // NOI18N
        btnGuardar5.setText("1E");
        btnGuardar5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar5ActionPerformed(evt);
            }
        });

        btnGuardar6.setBackground(new java.awt.Color(255, 0, 0));
        btnGuardar6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGuardar6.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosAerofly/plano.png"))); // NOI18N
        btnGuardar6.setText("1B");
        btnGuardar6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardar6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar6ActionPerformed(evt);
            }
        });

        btnGuardar7.setBackground(new java.awt.Color(153, 255, 153));
        btnGuardar7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGuardar7.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosAerofly/plano.png"))); // NOI18N
        btnGuardar7.setText("1B");
        btnGuardar7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardar7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar7ActionPerformed(evt);
            }
        });

        btnGuardar8.setBackground(new java.awt.Color(153, 255, 153));
        btnGuardar8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGuardar8.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosAerofly/plano.png"))); // NOI18N
        btnGuardar8.setText("1D");
        btnGuardar8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardar8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar8ActionPerformed(evt);
            }
        });

        btnGuardar9.setBackground(new java.awt.Color(153, 255, 153));
        btnGuardar9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGuardar9.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosAerofly/plano.png"))); // NOI18N
        btnGuardar9.setText("1F");
        btnGuardar9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardar9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar9ActionPerformed(evt);
            }
        });

        btnGuardar10.setBackground(new java.awt.Color(153, 255, 153));
        btnGuardar10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGuardar10.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosAerofly/plano.png"))); // NOI18N
        btnGuardar10.setText("4A");
        btnGuardar10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardar10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar10ActionPerformed(evt);
            }
        });

        btnGuardar11.setBackground(new java.awt.Color(153, 255, 153));
        btnGuardar11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGuardar11.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosAerofly/plano.png"))); // NOI18N
        btnGuardar11.setText("3A");
        btnGuardar11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardar11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar11ActionPerformed(evt);
            }
        });

        btnGuardar12.setBackground(new java.awt.Color(153, 255, 153));
        btnGuardar12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGuardar12.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosAerofly/plano.png"))); // NOI18N
        btnGuardar12.setText("2B");
        btnGuardar12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardar12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar12ActionPerformed(evt);
            }
        });

        btnGuardar13.setBackground(new java.awt.Color(153, 255, 153));
        btnGuardar13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGuardar13.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosAerofly/plano.png"))); // NOI18N
        btnGuardar13.setText("5A");
        btnGuardar13.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardar13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar13ActionPerformed(evt);
            }
        });

        btnGuardar14.setBackground(new java.awt.Color(153, 255, 153));
        btnGuardar14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGuardar14.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosAerofly/plano.png"))); // NOI18N
        btnGuardar14.setText("2A");
        btnGuardar14.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardar14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar14ActionPerformed(evt);
            }
        });

        btnGuardar15.setBackground(new java.awt.Color(153, 255, 153));
        btnGuardar15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGuardar15.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosAerofly/plano.png"))); // NOI18N
        btnGuardar15.setText("3B");
        btnGuardar15.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardar15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar15ActionPerformed(evt);
            }
        });

        btnGuardar16.setBackground(new java.awt.Color(153, 255, 153));
        btnGuardar16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGuardar16.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosAerofly/plano.png"))); // NOI18N
        btnGuardar16.setText("5B");
        btnGuardar16.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardar16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar16ActionPerformed(evt);
            }
        });

        btnGuardar17.setBackground(new java.awt.Color(1, 86, 192));
        btnGuardar17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGuardar17.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosAerofly/plano.png"))); // NOI18N
        btnGuardar17.setText("4B");
        btnGuardar17.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardar17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar17ActionPerformed(evt);
            }
        });

        btnGuardar18.setBackground(new java.awt.Color(153, 255, 153));
        btnGuardar18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGuardar18.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosAerofly/plano.png"))); // NOI18N
        btnGuardar18.setText("2B");
        btnGuardar18.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardar18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar18ActionPerformed(evt);
            }
        });

        btnGuardar19.setBackground(new java.awt.Color(153, 255, 153));
        btnGuardar19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGuardar19.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosAerofly/plano.png"))); // NOI18N
        btnGuardar19.setText("3B");
        btnGuardar19.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardar19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar19ActionPerformed(evt);
            }
        });

        btnGuardar20.setBackground(new java.awt.Color(255, 0, 0));
        btnGuardar20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGuardar20.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosAerofly/plano.png"))); // NOI18N
        btnGuardar20.setText("4B");
        btnGuardar20.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardar20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar20ActionPerformed(evt);
            }
        });

        btnGuardar21.setBackground(new java.awt.Color(153, 255, 153));
        btnGuardar21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGuardar21.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosAerofly/plano.png"))); // NOI18N
        btnGuardar21.setText("5B");
        btnGuardar21.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardar21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar21ActionPerformed(evt);
            }
        });

        btnGuardar22.setBackground(new java.awt.Color(153, 255, 153));
        btnGuardar22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGuardar22.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosAerofly/plano.png"))); // NOI18N
        btnGuardar22.setText("2B");
        btnGuardar22.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardar22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar22ActionPerformed(evt);
            }
        });

        btnGuardar23.setBackground(new java.awt.Color(153, 255, 153));
        btnGuardar23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGuardar23.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosAerofly/plano.png"))); // NOI18N
        btnGuardar23.setText("4D");
        btnGuardar23.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardar23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar23ActionPerformed(evt);
            }
        });

        btnGuardar24.setBackground(new java.awt.Color(255, 0, 0));
        btnGuardar24.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGuardar24.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosAerofly/plano.png"))); // NOI18N
        btnGuardar24.setText("3D");
        btnGuardar24.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardar24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar24ActionPerformed(evt);
            }
        });

        btnGuardar25.setBackground(new java.awt.Color(153, 255, 153));
        btnGuardar25.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGuardar25.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosAerofly/plano.png"))); // NOI18N
        btnGuardar25.setText("3D");
        btnGuardar25.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardar25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar25ActionPerformed(evt);
            }
        });

        btnGuardar26.setBackground(new java.awt.Color(153, 255, 153));
        btnGuardar26.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGuardar26.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosAerofly/plano.png"))); // NOI18N
        btnGuardar26.setText("2E");
        btnGuardar26.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardar26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar26ActionPerformed(evt);
            }
        });

        btnGuardar27.setBackground(new java.awt.Color(153, 255, 153));
        btnGuardar27.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGuardar27.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosAerofly/plano.png"))); // NOI18N
        btnGuardar27.setText("3E");
        btnGuardar27.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardar27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar27ActionPerformed(evt);
            }
        });

        btnGuardar28.setBackground(new java.awt.Color(153, 255, 153));
        btnGuardar28.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGuardar28.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosAerofly/plano.png"))); // NOI18N
        btnGuardar28.setText("5E");
        btnGuardar28.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardar28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar28ActionPerformed(evt);
            }
        });

        btnGuardar29.setBackground(new java.awt.Color(153, 255, 153));
        btnGuardar29.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGuardar29.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosAerofly/plano.png"))); // NOI18N
        btnGuardar29.setText("4E");
        btnGuardar29.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardar29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar29ActionPerformed(evt);
            }
        });

        btnGuardar30.setBackground(new java.awt.Color(153, 255, 153));
        btnGuardar30.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGuardar30.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosAerofly/plano.png"))); // NOI18N
        btnGuardar30.setText("2F");
        btnGuardar30.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardar30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar30ActionPerformed(evt);
            }
        });

        btnGuardar31.setBackground(new java.awt.Color(153, 255, 153));
        btnGuardar31.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGuardar31.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosAerofly/plano.png"))); // NOI18N
        btnGuardar31.setText("3F");
        btnGuardar31.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardar31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar31ActionPerformed(evt);
            }
        });

        btnGuardar32.setBackground(new java.awt.Color(153, 255, 153));
        btnGuardar32.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGuardar32.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosAerofly/plano.png"))); // NOI18N
        btnGuardar32.setText("5F");
        btnGuardar32.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardar32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar32ActionPerformed(evt);
            }
        });

        btnGuardar33.setBackground(new java.awt.Color(153, 255, 153));
        btnGuardar33.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGuardar33.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosAerofly/plano.png"))); // NOI18N
        btnGuardar33.setText("4F");
        btnGuardar33.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardar33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar33ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Asiento Seleccionado");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Información Del Asiento");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setText("Disponibilidad:");

        jButton1.setBackground(new java.awt.Color(153, 255, 153));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(1, 86, 192));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setText("Disponible");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel22.setText("Ocupado");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel23.setText("Seleccionado");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "4B" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jComboBox3.setBackground(new java.awt.Color(153, 255, 153));
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Disponible" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnGuardar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnGuardar14, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnGuardar4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(120, 120, 120)
                                .addComponent(btnGuardar7, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(171, 171, 171)
                                .addComponent(jLabel11))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(89, 89, 89)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                                .addGap(67, 67, 67)
                                                .addComponent(jLabel8)
                                                .addGap(69, 69, 69)
                                                .addComponent(jLabel9)))
                                        .addComponent(btnGuardar6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnGuardar12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addGap(13, 13, 13)
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                    .addComponent(jLabel18)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(btnGuardar10, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(btnGuardar17, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                    .addComponent(jLabel19)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(btnGuardar13, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(btnGuardar16, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                    .addComponent(jLabel17)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(btnGuardar11, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(btnGuardar15, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel20)
                                                        .addComponent(jLabel7)
                                                        .addComponent(jLabel6))
                                                    .addGap(0, 0, Short.MAX_VALUE)))))
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                    .addGap(59, 59, 59)
                                                    .addComponent(jLabel10)
                                                    .addGap(88, 88, 88)
                                                    .addComponent(jLabel12))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                                    .addGap(39, 39, 39)
                                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGap(36, 36, 36)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addGap(33, 33, 33)
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel1)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(btnGuardar19, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(btnGuardar18, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(btnGuardar20, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(btnGuardar21, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGap(38, 38, 38)
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                    .addComponent(btnGuardar25, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(btnGuardar29, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                                    .addComponent(btnGuardar23, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(btnGuardar28, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                    .addComponent(btnGuardar24, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(btnGuardar27, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                                    .addComponent(btnGuardar22, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(btnGuardar26, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                    .addComponent(btnGuardar8, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(42, 42, 42)
                                                    .addComponent(btnGuardar5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGap(36, 36, 36)
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(btnGuardar9, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btnGuardar30, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btnGuardar31, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btnGuardar33, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btnGuardar32, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btnGuardar1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addGap(27, 27, 27)
                                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addGap(27, 27, 27)
                                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(btnGuardar3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(290, 290, 290))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35))))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(btnGuardar2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14)
                    .addComponent(jLabel2))
                .addGap(5, 5, 5)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(btnGuardar4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGuardar6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGuardar7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGuardar5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGuardar8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGuardar9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnGuardar12, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnGuardar18, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnGuardar22, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnGuardar26, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnGuardar30, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(btnGuardar14, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel17)
                                        .addComponent(btnGuardar11, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnGuardar15, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnGuardar19, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnGuardar24, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnGuardar27, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnGuardar31, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(13, 13, 13))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addComponent(jLabel22))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addGap(3, 3, 3)
                                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(14, 14, 14)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel23)
                                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(btnGuardar10, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGuardar17, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGuardar20, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGuardar25, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGuardar29, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGuardar33, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(btnGuardar13, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGuardar16, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGuardar21, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGuardar23, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGuardar28, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGuardar32, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(88, 88, 88)))
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("A");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(341, 341, 341)
                    .addComponent(jLabel13)
                    .addContainerGap(482, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(189, 189, 189)
                    .addComponent(jLabel13)
                    .addContainerGap(430, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdUsuarioActionPerformed

    private void btnGuardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardar1ActionPerformed

    private void btnGuardar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardar2ActionPerformed

    private void btnGuardar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardar3ActionPerformed

    private void btnGuardar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardar4ActionPerformed

    private void btnGuardar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardar5ActionPerformed

    private void btnGuardar6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardar6ActionPerformed

    private void btnGuardar7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardar7ActionPerformed

    private void btnGuardar8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardar8ActionPerformed

    private void btnGuardar9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardar9ActionPerformed

    private void btnGuardar10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardar10ActionPerformed

    private void btnGuardar11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardar11ActionPerformed

    private void btnGuardar12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardar12ActionPerformed

    private void btnGuardar13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardar13ActionPerformed

    private void btnGuardar14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardar14ActionPerformed

    private void btnGuardar15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardar15ActionPerformed

    private void btnGuardar16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardar16ActionPerformed

    private void btnGuardar17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardar17ActionPerformed

    private void btnGuardar18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardar18ActionPerformed

    private void btnGuardar19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardar19ActionPerformed

    private void btnGuardar20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardar20ActionPerformed

    private void btnGuardar21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardar21ActionPerformed

    private void btnGuardar22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardar22ActionPerformed

    private void btnGuardar23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardar23ActionPerformed

    private void btnGuardar24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardar24ActionPerformed

    private void btnGuardar25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardar25ActionPerformed

    private void btnGuardar26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardar26ActionPerformed

    private void btnGuardar27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardar27ActionPerformed

    private void btnGuardar28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardar28ActionPerformed

    private void btnGuardar29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar29ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardar29ActionPerformed

    private void btnGuardar30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardar30ActionPerformed

    private void btnGuardar31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardar31ActionPerformed

    private void btnGuardar32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar32ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardar32ActionPerformed

    private void btnGuardar33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar33ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardar33ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmAsiento().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnGuardar1;
    public static javax.swing.JButton btnGuardar10;
    public static javax.swing.JButton btnGuardar11;
    public static javax.swing.JButton btnGuardar12;
    public static javax.swing.JButton btnGuardar13;
    public static javax.swing.JButton btnGuardar14;
    public static javax.swing.JButton btnGuardar15;
    public static javax.swing.JButton btnGuardar16;
    public static javax.swing.JButton btnGuardar17;
    public static javax.swing.JButton btnGuardar18;
    public static javax.swing.JButton btnGuardar19;
    public static javax.swing.JButton btnGuardar2;
    public static javax.swing.JButton btnGuardar20;
    public static javax.swing.JButton btnGuardar21;
    public static javax.swing.JButton btnGuardar22;
    public static javax.swing.JButton btnGuardar23;
    public static javax.swing.JButton btnGuardar24;
    public static javax.swing.JButton btnGuardar25;
    public static javax.swing.JButton btnGuardar26;
    public static javax.swing.JButton btnGuardar27;
    public static javax.swing.JButton btnGuardar28;
    public static javax.swing.JButton btnGuardar29;
    public static javax.swing.JButton btnGuardar3;
    public static javax.swing.JButton btnGuardar30;
    public static javax.swing.JButton btnGuardar31;
    public static javax.swing.JButton btnGuardar32;
    public static javax.swing.JButton btnGuardar33;
    public static javax.swing.JButton btnGuardar4;
    public static javax.swing.JButton btnGuardar5;
    public static javax.swing.JButton btnGuardar6;
    public static javax.swing.JButton btnGuardar7;
    public static javax.swing.JButton btnGuardar8;
    public static javax.swing.JButton btnGuardar9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JPanel jPanel3;
    public static javax.swing.JTextField txtIdUsuario;
    // End of variables declaration//GEN-END:variables
}
