/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author isabella
 */
public class frmMenu extends javax.swing.JFrame {

    /**
     * Creates new form frmMenu
     */
    public frmMenu() {
        initComponents();
        
    }
        
        public void configurarMenu(String rol) {

    if (rol.equalsIgnoreCase("CLIENTE")) {
        menuUsuarios.setVisible(false);
        menuVuelos.setVisible(false);
        menuReportes.setVisible(false);
        menuReservas.setVisible(true);
    }

    if (rol.equalsIgnoreCase("COLABORADOR")) {
        menuUsuarios.setVisible(false);
        menuVuelos.setVisible(true);
        menuReservas.setVisible(true);
        menuReportes.setVisible(false);
    }

    if (rol.equalsIgnoreCase("ADMINISTRADOR")) {
        menuUsuarios.setVisible(true);
        menuVuelos.setVisible(true);
        menuReservas.setVisible(true);
        menuReportes.setVisible(true);
    }
        
        }  
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuInicio = new javax.swing.JMenu();
        menuUsuarios = new javax.swing.JMenu();
        menuItemUsuarios = new javax.swing.JMenuItem();
        menuItemClientes = new javax.swing.JMenuItem();
        menuVuelos = new javax.swing.JMenu();
        menuItemAeropuertos = new javax.swing.JMenuItem();
        menuItemRutas = new javax.swing.JMenuItem();
        menuItemAviones = new javax.swing.JMenuItem();
        menuItemTarifas = new javax.swing.JMenuItem();
        menuReservas = new javax.swing.JMenu();
        menuItemAsientos = new javax.swing.JMenuItem();
        menuItemReservas = new javax.swing.JMenuItem();
        menuReportes = new javax.swing.JMenu();
        menuItemReportes = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Menu");
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(java.awt.Color.white);
        addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                formPropertyChange(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(13, 71, 161));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Sistema de Reserva de Vuelos");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(13, 71, 161));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("BIENVENIDO A AEROFLY");

        btnSalir.setBackground(new java.awt.Color(229, 57, 53));
        btnSalir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("Salir");
        btnSalir.setToolTipText("");
        btnSalir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 699, Short.MAX_VALUE)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(287, 287, 287))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(35, 35, 35)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosAerofly/FondoMenuu.png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel4.setVerifyInputWhenFocusTarget(false);

        jMenuBar1.setBackground(new java.awt.Color(13, 71, 161));
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setAlignmentX(0.0F);
        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jMenuBar1.setMargin(new java.awt.Insets(20, 5, 0, 0));
        jMenuBar1.setName(""); // NOI18N

        menuInicio.setForeground(new java.awt.Color(255, 255, 255));
        menuInicio.setText("Inicio");
        menuInicio.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        menuInicio.setMargin(new java.awt.Insets(20, 6, 3, 6));
        jMenuBar1.add(menuInicio);

        menuUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        menuUsuarios.setText("Usuarios");
        menuUsuarios.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N

        menuItemUsuarios.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menuItemUsuarios.setText("Usuarios");
        menuItemUsuarios.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        menuItemUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemUsuariosActionPerformed(evt);
            }
        });
        menuUsuarios.add(menuItemUsuarios);

        menuItemClientes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menuItemClientes.setText("Clientes");
        menuItemClientes.setHideActionText(true);
        menuItemClientes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        menuItemClientes.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        menuUsuarios.add(menuItemClientes);

        jMenuBar1.add(menuUsuarios);

        menuVuelos.setForeground(new java.awt.Color(255, 255, 255));
        menuVuelos.setText("Vuelos");
        menuVuelos.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N

        menuItemAeropuertos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menuItemAeropuertos.setText("Aeropuertos");
        menuVuelos.add(menuItemAeropuertos);

        menuItemRutas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menuItemRutas.setText("Rutas");
        menuVuelos.add(menuItemRutas);

        menuItemAviones.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menuItemAviones.setText("Aviones");
        menuVuelos.add(menuItemAviones);

        menuItemTarifas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menuItemTarifas.setText("Tarifas");
        menuVuelos.add(menuItemTarifas);

        jMenuBar1.add(menuVuelos);

        menuReservas.setForeground(new java.awt.Color(255, 255, 255));
        menuReservas.setText("Reservas");
        menuReservas.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N

        menuItemAsientos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menuItemAsientos.setText("Asientos");
        menuReservas.add(menuItemAsientos);

        menuItemReservas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menuItemReservas.setText("Reservas");
        menuReservas.add(menuItemReservas);

        jMenuBar1.add(menuReservas);

        menuReportes.setForeground(new java.awt.Color(255, 255, 255));
        menuReportes.setText("Reportes");
        menuReportes.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N

        menuItemReportes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menuItemReportes.setText("Reportes");
        menuItemReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemReportesActionPerformed(evt);
            }
        });
        menuReportes.add(menuItemReportes);

        jMenuBar1.add(menuReportes);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemUsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemUsuariosActionPerformed

    private void formPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_formPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_formPropertyChange

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    private void menuItemReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemReportesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemReportesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JMenu menuInicio;
    public javax.swing.JMenuItem menuItemAeropuertos;
    public javax.swing.JMenuItem menuItemAsientos;
    public javax.swing.JMenuItem menuItemAviones;
    public javax.swing.JMenuItem menuItemClientes;
    public javax.swing.JMenuItem menuItemReportes;
    public javax.swing.JMenuItem menuItemReservas;
    public javax.swing.JMenuItem menuItemRutas;
    public javax.swing.JMenuItem menuItemTarifas;
    public javax.swing.JMenuItem menuItemUsuarios;
    public javax.swing.JMenu menuReportes;
    public javax.swing.JMenu menuReservas;
    public javax.swing.JMenu menuUsuarios;
    public javax.swing.JMenu menuVuelos;
    // End of variables declaration//GEN-END:variables
}
