/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author victo
 */
public class frmReportes extends javax.swing.JFrame {
   
   private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmReportes.class.getName());

   /**
    * Creates new form frmReportes
    */
   public frmReportes() {
      initComponents();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jScrollPane1 = new javax.swing.JScrollPane();
      jList1 = new javax.swing.JList<>();
      jSlider1 = new javax.swing.JSlider();
      jSpinner1 = new javax.swing.JSpinner();
      jMenuItem1 = new javax.swing.JMenuItem();
      jScrollPane2 = new javax.swing.JScrollPane();
      jTable1 = new javax.swing.JTable();
      jScrollPane3 = new javax.swing.JScrollPane();
      jEditorPane1 = new javax.swing.JEditorPane();
      jSeparator1 = new javax.swing.JSeparator();
      jFormattedTextField1 = new javax.swing.JFormattedTextField();
      jScrollPane4 = new javax.swing.JScrollPane();
      jTree1 = new javax.swing.JTree();
      jToggleButton1 = new javax.swing.JToggleButton();
      jComboBox1 = new javax.swing.JComboBox<>();
      jScrollPane5 = new javax.swing.JScrollPane();
      jTable2 = new javax.swing.JTable();
      jPanel3 = new javax.swing.JPanel();
      jLabel2 = new javax.swing.JLabel();
      jLabel3 = new javax.swing.JLabel();
      jLabel4 = new javax.swing.JLabel();
      txtTipoReporte = new javax.swing.JTextField();
      txtFechaInicio = new javax.swing.JTextField();
      txtFechaFin = new javax.swing.JTextField();
      btnGenerar = new javax.swing.JButton();
      btnLimpiar = new javax.swing.JButton();
      jLabel1 = new javax.swing.JLabel();
      jScrollPane6 = new javax.swing.JScrollPane();
      tblReportes = new javax.swing.JTable();

      jList1.setModel(new javax.swing.AbstractListModel<String>() {
         String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
         public int getSize() { return strings.length; }
         public String getElementAt(int i) { return strings[i]; }
      });
      jScrollPane1.setViewportView(jList1);

      jMenuItem1.setText("jMenuItem1");

      jTable1.setModel(new javax.swing.table.DefaultTableModel(
         new Object [][] {
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null}
         },
         new String [] {
            "Title 1", "Title 2", "Title 3", "Title 4"
         }
      ));
      jScrollPane2.setViewportView(jTable1);

      jScrollPane3.setViewportView(jEditorPane1);

      jFormattedTextField1.setText("jFormattedTextField1");

      jScrollPane4.setViewportView(jTree1);

      jToggleButton1.setText("jToggleButton1");

      jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

      jTable2.setModel(new javax.swing.table.DefaultTableModel(
         new Object [][] {
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null}
         },
         new String [] {
            "Title 1", "Title 2", "Title 3", "Title 4"
         }
      ));
      jScrollPane5.setViewportView(jTable2);

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

      jPanel3.setBackground(new java.awt.Color(255, 255, 255));

      jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
      jLabel2.setText("Tipo de Reporte:");

      jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
      jLabel3.setText("Fecha Inicio:");

      jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
      jLabel4.setText("Fecha Fin:");

      txtTipoReporte.setBackground(new java.awt.Color(227, 242, 253));
      txtTipoReporte.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
      txtTipoReporte.addActionListener(this::txtTipoReporteActionPerformed);

      txtFechaInicio.setBackground(new java.awt.Color(227, 242, 253));
      txtFechaInicio.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
      txtFechaInicio.addActionListener(this::txtFechaInicioActionPerformed);

      txtFechaFin.setBackground(new java.awt.Color(227, 242, 253));
      txtFechaFin.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
      txtFechaFin.addActionListener(this::txtFechaFinActionPerformed);

      btnGenerar.setBackground(new java.awt.Color(13, 71, 161));
      btnGenerar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
      btnGenerar.setForeground(new java.awt.Color(255, 255, 255));
      btnGenerar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosAerofly/lapiz (2).png"))); // NOI18N
      btnGenerar.setText("Generar");
      btnGenerar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
      btnGenerar.addActionListener(this::btnGenerarActionPerformed);

      btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosAerofly/escoba.png"))); // NOI18N
      btnLimpiar.setText("Limpiar");
      btnLimpiar.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(21, 101, 192), null));
      btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);

      jLabel1.setBackground(new java.awt.Color(51, 255, 51));
      jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
      jLabel1.setForeground(new java.awt.Color(21, 101, 192));
      jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosAerofly/salidaAvion.png"))); // NOI18N
      jLabel1.setText("Reportes");
      jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
      jLabel1.setIconTextGap(10);
      jLabel1.setInheritsPopupMenu(false);

      tblReportes.setModel(new javax.swing.table.DefaultTableModel(
         new Object [][] {
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null}
         },
         new String [] {
            "Title 1", "Title 2", "Title 3", "Title 4"
         }
      ));
      jScrollPane6.setViewportView(tblReportes);

      javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
      jPanel3.setLayout(jPanel3Layout);
      jPanel3Layout.setHorizontalGroup(
         jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel3Layout.createSequentialGroup()
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel3Layout.createSequentialGroup()
                  .addContainerGap()
                  .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
               .addGroup(jPanel3Layout.createSequentialGroup()
                  .addGap(45, 45, 45)
                  .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(jLabel3)
                     .addComponent(jLabel4)
                     .addComponent(jLabel2))
                  .addGap(0, 0, Short.MAX_VALUE)))
            .addContainerGap())
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                  .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                     .addComponent(txtFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(txtFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(txtTipoReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addGap(95, 95, 95))
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                  .addComponent(btnGenerar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(76, 76, 76)
                  .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(197, 197, 197))))
         .addGroup(jPanel3Layout.createSequentialGroup()
            .addGap(24, 24, 24)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 45, Short.MAX_VALUE))
      );
      jPanel3Layout.setVerticalGroup(
         jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel3Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(txtTipoReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel2))
            .addGap(37, 37, 37)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(txtFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel3))
            .addGap(37, 37, 37)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(txtFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel4))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(btnGenerar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(38, 38, 38)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(195, 195, 195))
      );

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void txtFechaInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaInicioActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_txtFechaInicioActionPerformed

   private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_btnGenerarActionPerformed

   private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_btnLimpiarActionPerformed

   private void txtTipoReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipoReporteActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_txtTipoReporteActionPerformed

   private void txtFechaFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaFinActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_txtFechaFinActionPerformed

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
         logger.log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(() -> new frmReportes().setVisible(true));
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   public static javax.swing.JButton btnGenerar;
   public static javax.swing.JButton btnLimpiar;
   private javax.swing.JComboBox<String> jComboBox1;
   private javax.swing.JEditorPane jEditorPane1;
   private javax.swing.JFormattedTextField jFormattedTextField1;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JList<String> jList1;
   private javax.swing.JMenuItem jMenuItem1;
   public static javax.swing.JPanel jPanel3;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JScrollPane jScrollPane2;
   private javax.swing.JScrollPane jScrollPane3;
   private javax.swing.JScrollPane jScrollPane4;
   private javax.swing.JScrollPane jScrollPane5;
   private javax.swing.JScrollPane jScrollPane6;
   private javax.swing.JSeparator jSeparator1;
   private javax.swing.JSlider jSlider1;
   private javax.swing.JSpinner jSpinner1;
   private javax.swing.JTable jTable1;
   private javax.swing.JTable jTable2;
   private javax.swing.JToggleButton jToggleButton1;
   private javax.swing.JTree jTree1;
   public static javax.swing.JTable tblReportes;
   public static javax.swing.JTextField txtFechaFin;
   public static javax.swing.JTextField txtFechaInicio;
   public static javax.swing.JTextField txtTipoReporte;
   // End of variables declaration//GEN-END:variables
}
